---
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    env_file: .env
    command: python -m flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build: .
    env_file: .env
    command: python -m celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis
    user: "1000:1000"  # or the uid:gid you created in Dockerfile
